version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      retries: 5

  gateway-1:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    environment:
      - REDIS_NODES=redis://redis:6379/0
      - ASYNC_AUDIT=1
    depends_on:
      redis:
        condition: service_healthy

  gateway-2:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8801:8800"
    environment:
      - REDIS_NODES=redis://redis:6379/0
      - ASYNC_AUDIT=1
    depends_on:
      redis:
        condition: service_healthy

  gateway-3:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8802:8800"
    environment:
      - REDIS_NODES=redis://redis:6379/0
      - ASYNC_AUDIT=1
    depends_on:
      redis:
        condition: service_healthy

  worker-1:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_NODES=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  worker-2:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_NODES=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
